### ISSUE TITLE
 Missing hint for struct StructProperty

### ISSUE THREAD

**Issue by jashnniloofar** [scottanderson/gvas2json#61]
There is an issue parsing save files from the "Medieval Dynasty" game. I tried to convert save file to json I have this error:
"Error: Missing hint for struct StructProperty at path LandscapeData.MapProperty.Value.StructProperty at position 0x6b1"

I attached .sav file.
[Quicksave.zip](https://github.com/user-attachments/files/17258225/Quicksave.zip)

**Comment by scottanderson** [comment]
This library is a thin wrapper around the `gvas` crate. See https://github.com/localcc/gvas/issues/103 for the underlying issue.
